# Generated by Django 6.0.5 on 2026-05-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INCOME', 'Income'), ('BILLS', 'Bills'), ('SUBSCRIPTIONS', 'Subscriptions'), ('EXPENSES', 'Expenses'), ('SAVINGS_INVESTMENTS', 'Savings & Investments'), ('DEBT', 'Debt'), ('CREDIT', 'Credit')], max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_day', models.IntegerField(blank=True, help_text='Optional recurring due day (1-31)', null=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tracker.financialpillar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['pillar', 'name'],
                'unique_together': {('user', 'pillar', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starting_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_contribution_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='tracker.subcategory')),
            ],
            options={
                'ordering': ['subcategory__pillar', 'subcategory__name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_targets', to='tracker.subcategory')),
            ],
            options={
                'ordering': ['year', 'month', 'subcategory__pillar', 'subcategory__name'],
                'unique_together': {('subcategory', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DebtBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_balances', to='tracker.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Debt Balance Histories',
                'ordering': ['year', 'month', 'subcategory__name'],
                'unique_together': {('subcategory', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_credit_type', models.ForeignKey(blank=True, help_text='Credit/Debt subcategory if funded via plastic/loans', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_transactions', to='tracker.subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tracker.financialpillar')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tracker.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='tracker_tra_user_id_c79925_idx'), models.Index(fields=['user', 'category'], name='tracker_tra_user_id_ec3946_idx')],
            },
        ),
    ]
