# Generated by Django 6.0.5 on 2026-06-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_transactionlog_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtbalancehistory',
            name='payment_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
