# Generated by Django 6.0.5 on 2026-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_debtbalancehistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='debt_history_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
