# Generated by Django 6.0.5 on 2026-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_transactionlog_debt_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtbalancehistory',
            name='is_receivable',
            field=models.BooleanField(default=False),
        ),
    ]
