# Generated by Django 6.0.5 on 2026-06-03 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INCOME', 'Income'), ('BILLS', 'Bills'), ('SUBSCRIPTIONS', 'Subscriptions'), ('EXPENSES', 'Expenses'), ('SAVINGS_INVESTMENTS', 'Savings & Investments'), ('DEBT', 'Debt'), ('CREDIT', 'Credit')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_day', models.IntegerField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tracker.financialpillar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'unique_together': {('user', 'pillar', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_credit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='tracker.subcategory')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.financialpillar')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starting_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_contribution_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(limit_choices_to={'pillar__name': 'SAVINGS_INVESTMENTS'}, on_delete=django.db.models.deletion.CASCADE, to='tracker.subcategory')),
            ],
            options={
                'unique_together': {('user', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudgetTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subcategory')),
            ],
            options={
                'unique_together': {('user', 'subcategory', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DebtBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_made', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Debt Balance Histories',
                'unique_together': {('user', 'subcategory', 'year', 'month')},
            },
        ),
    ]
