# Generated by Django 6.0.5 on 2026-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_transactionlog_is_deleted_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='payment_mode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
