# Generated by Django 6.0.5 on 2026-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_debtbalancehistory_is_receivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
